// ======================================================================
// \title  ICM20948TesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for ICM20948 component test harness helper functions
// ======================================================================

#include "ICM20948Tester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void ICM20948Tester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_logOut_OutputPort(
      0,
      this->get_from_logOut(0)
    );

    this->component.set_logTextOut_OutputPort(
      0,
      this->get_from_logTextOut(0)
    );

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_getAccelData(
      0,
      this->component.get_getAccelData_InputPort(0)
    );

    this->connect_to_getGyroData(
      0,
      this->component.get_getGyroData_InputPort(0)
    );

    this->connect_to_getMagnData(
      0,
      this->component.get_getMagnData_InputPort(0)
    );

    this->connect_to_getQuatData(
      0,
      this->component.get_getQuatData_InputPort(0)
    );

    this->connect_to_pollQuatData(
      0,
      this->component.get_pollQuatData_InputPort(0)
    );

    this->connect_to_pollRawData(
      0,
      this->component.get_pollRawData_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_intPin_OutputPort(
      0,
      this->get_from_intPin(0)
    );

    this->component.set_read_OutputPort(
      0,
      this->get_from_read(0)
    );

    this->component.set_write_OutputPort(
      0,
      this->get_from_write(0)
    );
  }

  void ICM20948Tester ::
    initComponents()
  {
    this->init();
    this->component.init(ICM20948Tester::TEST_INSTANCE_ID);
  }

}
