// ======================================================================
// \title  FRAMManagerTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for FRAMManager component test harness helper functions
// ======================================================================

#include "FRAMManagerTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void FRAMManagerTester ::
    connectPorts()
  {
    // Connect special input ports

    this->connect_to_cmdIn(
      0,
      this->component.get_cmdIn_InputPort(0)
    );

    // Connect special output ports

    this->component.set_cmdRegOut_OutputPort(
      0,
      this->get_from_cmdRegOut(0)
    );

    this->component.set_cmdResponseOut_OutputPort(
      0,
      this->get_from_cmdResponseOut(0)
    );

    this->component.set_logOut_OutputPort(
      0,
      this->get_from_logOut(0)
    );

    this->component.set_logTextOut_OutputPort(
      0,
      this->get_from_logTextOut(0)
    );

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_requestRead(
      0,
      this->component.get_requestRead_InputPort(0)
    );

    this->connect_to_requestSleep(
      0,
      this->component.get_requestSleep_InputPort(0)
    );

    this->connect_to_requestWakeup(
      0,
      this->component.get_requestWakeup_InputPort(0)
    );

    this->connect_to_requestWrite(
      0,
      this->component.get_requestWrite_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_read_OutputPort(
      0,
      this->get_from_read(0)
    );

    this->component.set_reinit_OutputPort(
      0,
      this->get_from_reinit(0)
    );

    this->component.set_sleep_OutputPort(
      0,
      this->get_from_sleep(0)
    );

    this->component.set_status_OutputPort(
      0,
      this->get_from_status(0)
    );

    this->component.set_wakeup_OutputPort(
      0,
      this->get_from_wakeup(0)
    );

    this->component.set_write_OutputPort(
      0,
      this->get_from_write(0)
    );
  }

  void FRAMManagerTester ::
    initComponents()
  {
    this->init();
    this->component.init(FRAMManagerTester::TEST_INSTANCE_QUEUE_DEPTH, FRAMManagerTester::TEST_INSTANCE_ID);
  }

}
