// ======================================================================
// \title  STS21TesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for STS21 component test harness helper functions
// ======================================================================

#include "STS21Tester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void STS21Tester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_logOut_OutputPort(
      0,
      this->get_from_logOut(0)
    );

    this->component.set_logTextOut_OutputPort(
      0,
      this->get_from_logTextOut(0)
    );

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_getTemperature(
      0,
      this->component.get_getTemperature_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_read_OutputPort(
      0,
      this->get_from_read(0)
    );

    this->component.set_write_OutputPort(
      0,
      this->get_from_write(0)
    );
  }

  void STS21Tester ::
    initComponents()
  {
    this->init();
    this->component.init(STS21Tester::TEST_INSTANCE_ID);
  }

}
