// ======================================================================
// \title  IOExpanderTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for IOExpander component test harness helper functions
// ======================================================================

#include "IOExpanderTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void IOExpanderTester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_logOut_OutputPort(
      0,
      this->get_from_logOut(0)
    );

    this->component.set_logTextOut_OutputPort(
      0,
      this->get_from_logTextOut(0)
    );

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_calibrateADCOffset(
      0,
      this->component.get_calibrateADCOffset_InputPort(0)
    );

    this->connect_to_getNumOfThresholdHit(
      0,
      this->component.get_getNumOfThresholdHit_InputPort(0)
    );

    this->connect_to_readAnalogInput(
      0,
      this->component.get_readAnalogInput_InputPort(0)
    );

    this->connect_to_readDigitalMultipleInputs(
      0,
      this->component.get_readDigitalMultipleInputs_InputPort(0)
    );

    this->connect_to_readDigitalSingleInput(
      0,
      this->component.get_readDigitalSingleInput_InputPort(0)
    );

    this->connect_to_run(
      0,
      this->component.get_run_InputPort(0)
    );

    this->connect_to_writeDigitalMultipleOutputs(
      0,
      this->component.get_writeDigitalMultipleOutputs_InputPort(0)
    );

    this->connect_to_writeDigitalSingleOutput(
      0,
      this->component.get_writeDigitalSingleOutput_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_alert_OutputPort(
      0,
      this->get_from_alert(0)
    );

    this->component.set_read_OutputPort(
      0,
      this->get_from_read(0)
    );

    this->component.set_write_OutputPort(
      0,
      this->get_from_write(0)
    );

    this->component.set_writeRead_OutputPort(
      0,
      this->get_from_writeRead(0)
    );
  }

  void IOExpanderTester ::
    initComponents()
  {
    this->init();
    this->component.init(IOExpanderTester::TEST_INSTANCE_QUEUE_DEPTH, IOExpanderTester::TEST_INSTANCE_ID);
  }

}
