// ======================================================================
// \title  NORDriverTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for NORDriver component test harness helper functions
// ======================================================================

#include "NORDriverTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void NORDriverTester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_logOut_OutputPort(
      0,
      this->get_from_logOut(0)
    );

    this->component.set_logTextOut_OutputPort(
      0,
      this->get_from_logTextOut(0)
    );

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_erase(
      0,
      this->component.get_erase_InputPort(0)
    );

    this->connect_to_getMemorySize(
      0,
      this->component.get_getMemorySize_InputPort(0)
    );

    this->connect_to_getSectorSize(
      0,
      this->component.get_getSectorSize_InputPort(0)
    );

    this->connect_to_read(
      0,
      this->component.get_read_InputPort(0)
    );

    this->connect_to_write(
      0,
      this->component.get_write_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_commandWrite_OutputPort(
      0,
      this->get_from_commandWrite(0)
    );

    this->component.set_memoryRead_OutputPort(
      0,
      this->get_from_memoryRead(0)
    );

    this->component.set_memoryWrite_OutputPort(
      0,
      this->get_from_memoryWrite(0)
    );

    this->component.set_registerRead_OutputPort(
      0,
      this->get_from_registerRead(0)
    );

    this->component.set_registerWrite_OutputPort(
      0,
      this->get_from_registerWrite(0)
    );
  }

  void NORDriverTester ::
    initComponents()
  {
    this->init();
    this->component.init(NORDriverTester::TEST_INSTANCE_ID);
  }

}
