// ======================================================================
// \title  DPS310TesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for DPS310 component test harness helper functions
// ======================================================================

#include "DPS310Tester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void DPS310Tester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_logOut_OutputPort(
      0,
      this->get_from_logOut(0)
    );

    this->component.set_logTextOut_OutputPort(
      0,
      this->get_from_logTextOut(0)
    );

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_getPressure(
      0,
      this->component.get_getPressure_InputPort(0)
    );

    this->connect_to_getTemperature(
      0,
      this->component.get_getTemperature_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_read_OutputPort(
      0,
      this->get_from_read(0)
    );

    this->component.set_write_OutputPort(
      0,
      this->get_from_write(0)
    );
  }

  void DPS310Tester ::
    initComponents()
  {
    this->init();
    this->component.init(DPS310Tester::TEST_INSTANCE_ID);
  }

}
