// ======================================================================
// \title  FRAMDriverTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for FRAMDriver component test harness helper functions
// ======================================================================

#include "FRAMDriverTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void FRAMDriverTester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_logOut_OutputPort(
      0,
      this->get_from_logOut(0)
    );

    this->component.set_logTextOut_OutputPort(
      0,
      this->get_from_logTextOut(0)
    );

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_read(
      0,
      this->component.get_read_InputPort(0)
    );

    this->connect_to_reinit(
      0,
      this->component.get_reinit_InputPort(0)
    );

    this->connect_to_sleep(
      0,
      this->component.get_sleep_InputPort(0)
    );

    this->connect_to_wakeup(
      0,
      this->component.get_wakeup_InputPort(0)
    );

    this->connect_to_write(
      0,
      this->component.get_write_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_chipSelect_OutputPort(
      0,
      this->get_from_chipSelect(0)
    );

    this->component.set_driver_read_OutputPort(
      0,
      this->get_from_driver_read(0)
    );

    this->component.set_driver_reinit_OutputPort(
      0,
      this->get_from_driver_reinit(0)
    );

    this->component.set_driver_write_OutputPort(
      0,
      this->get_from_driver_write(0)
    );
  }

  void FRAMDriverTester ::
    initComponents()
  {
    this->init();
    this->component.init(FRAMDriverTester::TEST_INSTANCE_ID);
  }

}
