// ======================================================================
// \title  ExtBatManagerTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for ExtBatManager component test harness helper functions
// ======================================================================

#include "ExtBatManagerTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void ExtBatManagerTester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_logOut_OutputPort(
      0,
      this->get_from_logOut(0)
    );

    this->component.set_logTextOut_OutputPort(
      0,
      this->get_from_logTextOut(0)
    );

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    this->component.set_tlmOut_OutputPort(
      0,
      this->get_from_tlmOut(0)
    );

    // Connect typed input ports

    this->connect_to_getVoltage(
      0,
      this->component.get_getVoltage_InputPort(0)
    );

    this->connect_to_run(
      0,
      this->component.get_run_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_enablePin_OutputPort(
      0,
      this->get_from_enablePin(0)
    );

    this->component.set_getVoltageValue_OutputPort(
      0,
      this->get_from_getVoltageValue(0)
    );
  }

  void ExtBatManagerTester ::
    initComponents()
  {
    this->init();
    this->component.init(ExtBatManagerTester::TEST_INSTANCE_QUEUE_DEPTH, ExtBatManagerTester::TEST_INSTANCE_ID);
  }

}
