// ======================================================================
// \title  NORManagerTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for NORManager component test harness helper functions
// ======================================================================

#include "NORManagerTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void NORManagerTester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_getOutMemorySize(
      0,
      this->component.get_getOutMemorySize_InputPort(0)
    );

    this->connect_to_getOutSectorSize(
      0,
      this->component.get_getOutSectorSize_InputPort(0)
    );

    this->connect_to_requestErase(
      0,
      this->component.get_requestErase_InputPort(0)
    );

    this->connect_to_requestRead(
      0,
      this->component.get_requestRead_InputPort(0)
    );

    this->connect_to_requestWrite(
      0,
      this->component.get_requestWrite_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_erase_OutputPort(
      0,
      this->get_from_erase(0)
    );

    this->component.set_eraseStatus_OutputPort(
      0,
      this->get_from_eraseStatus(0)
    );

    this->component.set_getInMemorySize_OutputPort(
      0,
      this->get_from_getInMemorySize(0)
    );

    this->component.set_getInSectorSize_OutputPort(
      0,
      this->get_from_getInSectorSize(0)
    );

    this->component.set_read_OutputPort(
      0,
      this->get_from_read(0)
    );

    this->component.set_readStatus_OutputPort(
      0,
      this->get_from_readStatus(0)
    );

    this->component.set_write_OutputPort(
      0,
      this->get_from_write(0)
    );

    this->component.set_writeStatus_OutputPort(
      0,
      this->get_from_writeStatus(0)
    );
  }

  void NORManagerTester ::
    initComponents()
  {
    this->init();
    this->component.init(NORManagerTester::TEST_INSTANCE_QUEUE_DEPTH, NORManagerTester::TEST_INSTANCE_ID);
  }

}
