// ======================================================================
// \title  BNO055TesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for BNO055 component test harness helper functions
// ======================================================================

#include "BNO055Tester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void BNO055Tester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_logOut_OutputPort(
      0,
      this->get_from_logOut(0)
    );

    this->component.set_logTextOut_OutputPort(
      0,
      this->get_from_logTextOut(0)
    );

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_getAccelData(
      0,
      this->component.get_getAccelData_InputPort(0)
    );

    this->connect_to_getGyroData(
      0,
      this->component.get_getGyroData_InputPort(0)
    );

    this->connect_to_getMagnData(
      0,
      this->component.get_getMagnData_InputPort(0)
    );

    this->connect_to_getQuatData(
      0,
      this->component.get_getQuatData_InputPort(0)
    );

    this->connect_to_getRawData(
      0,
      this->component.get_getRawData_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_getNumOfBytes_OutputPort(
      0,
      this->get_from_getNumOfBytes(0)
    );

    this->component.set_read_OutputPort(
      0,
      this->get_from_read(0)
    );

    this->component.set_write_OutputPort(
      0,
      this->get_from_write(0)
    );
  }

  void BNO055Tester ::
    initComponents()
  {
    this->init();
    this->component.init(BNO055Tester::TEST_INSTANCE_ID);
  }

}
