// ======================================================================
// \title  EnvSensManagerTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for EnvSensManager component test harness helper functions
// ======================================================================

#include "EnvSensManagerTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void EnvSensManagerTester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_getSensorData(
      0,
      this->component.get_getSensorData_InputPort(0)
    );

    this->connect_to_run(
      0,
      this->component.get_run_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_getPressuretDPS310_OutputPort(
      0,
      this->get_from_getPressuretDPS310(0)
    );

    this->component.set_getTemperatureDPS310_OutputPort(
      0,
      this->get_from_getTemperatureDPS310(0)
    );

    this->component.set_getTemperatureSTS21_OutputPort(
      0,
      this->get_from_getTemperatureSTS21(0)
    );

    this->component.set_getTemperaturePolynomNTC_OutputPort(
      0,
      this->get_from_getTemperaturePolynomNTC(0)
    );

    this->component.set_getTemperatureTableNTC_OutputPort(
      0,
      this->get_from_getTemperatureTableNTC(0)
    );

  }

  void EnvSensManagerTester ::
    initComponents()
  {
    this->init();
    this->component.init(EnvSensManagerTester::TEST_INSTANCE_QUEUE_DEPTH, EnvSensManagerTester::TEST_INSTANCE_ID);
  }

}
