// ======================================================================
// \title  IMU2ManagerTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for IMU2Manager component test harness helper functions
// ======================================================================

#include "IMU2ManagerTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void IMU2ManagerTester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_getData(
      0,
      this->component.get_getData_InputPort(0)
    );

    this->connect_to_getQuaternion(
      0,
      this->component.get_getQuaternion_InputPort(0)
    );

    this->connect_to_run(
      0,
      this->component.get_run_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_getAccelData_OutputPort(
      0,
      this->get_from_getAccelData(0)
    );

    this->component.set_getGyroData_OutputPort(
      0,
      this->get_from_getGyroData(0)
    );

    this->component.set_getMagnData_OutputPort(
      0,
      this->get_from_getMagnData(0)
    );

    this->component.set_getQuatData_OutputPort(
      0,
      this->get_from_getQuatData(0)
    );

    this->component.set_getRawData_OutputPort(
      0,
      this->get_from_getRawData(0)
    );

    this->component.set_pollQuatData_OutputPort(
      0,
      this->get_from_pollQuatData(0)
    );

    this->component.set_pollRawData_OutputPort(
      0,
      this->get_from_pollRawData(0)
    );
  }

  void IMU2ManagerTester ::
    initComponents()
  {
    this->init();
    this->component.init(IMU2ManagerTester::TEST_INSTANCE_QUEUE_DEPTH, IMU2ManagerTester::TEST_INSTANCE_ID);
  }

}
