// ======================================================================
// \title  ComModuleTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for ComModule component test harness helper functions
// ======================================================================

#include "ComModuleTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void ComModuleTester ::
    connectPorts()
  {
    // Connect typed input ports

    this->connect_to_schedIn(
      0,
      this->component.get_schedIn_InputPort(0)
    );

    this->connect_to_send(
      0,
      this->component.get_send_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_allocate_OutputPort(
      0,
      this->get_from_allocate(0)
    );

    this->component.set_deallocate_OutputPort(
      0,
      this->get_from_deallocate(0)
    );

    this->component.set_read_OutputPort(
      0,
      this->get_from_read(0)
    );

    this->component.set_ready_OutputPort(
      0,
      this->get_from_ready(0)
    );

    this->component.set_recv_OutputPort(
      0,
      this->get_from_recv(0)
    );

    this->component.set_write_OutputPort(
      0,
      this->get_from_write(0)
    );
  }

  void ComModuleTester ::
    initComponents()
  {
    this->init();
    this->component.init(ComModuleTester::TEST_INSTANCE_ID);
  }

}
