// ======================================================================
// \title  NTCTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for NTC component test harness helper functions
// ======================================================================

#include "NTCTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void NTCTester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_getPolynomTemperature(
      0,
      this->component.get_getPolynomTemperature_InputPort(0)
    );

    this->connect_to_getTableTemperature(
      0,
      this->component.get_getTableTemperature_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_getADCCode_OutputPort(
      0,
      this->get_from_getADCCode(0)
    );

    this->component.set_getADCMax_OutputPort(
      0,
      this->get_from_getADCMax(0)
    );

    this->component.set_getVoltageReference_OutputPort(
      0,
      this->get_from_getVoltageReference(0)
    );

    this->component.set_getVoltageValue_OutputPort(
      0,
      this->get_from_getVoltageValue(0)
    );
  }

  void NTCTester ::
    initComponents()
  {
    this->init();
    this->component.init(NTCTester::TEST_INSTANCE_ID);
  }

}
