// ======================================================================
// \title  IMUManagerTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for IMUManager component test harness helper functions
// ======================================================================

#include "IMUManagerTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void IMUManagerTester ::
    connectPorts()
  {
    // Connect special output ports

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    // Connect typed input ports

    this->connect_to_getBNO055Data(
      0,
      this->component.get_getBNO055Data_InputPort(0)
    );

    this->connect_to_getBNO055Quaternion(
      0,
      this->component.get_getBNO055Quaternion_InputPort(0)
    );

    this->connect_to_getICM20948Data(
      0,
      this->component.get_getICM20948Data_InputPort(0)
    );

    this->connect_to_getICM20948Quaternion(
      0,
      this->component.get_getICM20948Quaternion_InputPort(0)
    );

    this->connect_to_run(
      0,
      this->component.get_run_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_getAccelDataBNO055_OutputPort(
      0,
      this->get_from_getAccelDataBNO055(0)
    );

    this->component.set_getAccelDataICM20948_OutputPort(
      0,
      this->get_from_getAccelDataICM20948(0)
    );

    this->component.set_getGyroDataBNO055_OutputPort(
      0,
      this->get_from_getGyroDataBNO055(0)
    );

    this->component.set_getGyroDataICM20948_OutputPort(
      0,
      this->get_from_getGyroDataICM20948(0)
    );

    this->component.set_getMagnDataBNO055_OutputPort(
      0,
      this->get_from_getMagnDataBNO055(0)
    );

    this->component.set_getMagnDataICM20948_OutputPort(
      0,
      this->get_from_getMagnDataICM20948(0)
    );

    this->component.set_getQuatDataBNO055_OutputPort(
      0,
      this->get_from_getQuatDataBNO055(0)
    );

    this->component.set_getQuatDataICM20948_OutputPort(
      0,
      this->get_from_getQuatDataICM20948(0)
    );

    this->component.set_pollQuatData_OutputPort(
      0,
      this->get_from_pollQuatData(0)
    );

    this->component.set_pollRawData_OutputPort(
      0,
      this->get_from_pollRawData(0)
    );
  }

  void IMUManagerTester ::
    initComponents()
  {
    this->init();
    this->component.init(IMUManagerTester::TEST_INSTANCE_QUEUE_DEPTH, IMUManagerTester::TEST_INSTANCE_ID);
  }

}
